### PR TITLE
Add ZoneId converter

### PR DESCRIPTION
**Pull request by pavanpvpk**

### CODE REVIEW

**Comment by gkopff** [comment]
Hi @pavanpvpk - sorry to take so long to get back to you, I've been travelling.

I have a couple of points of feedback:
 - could we please limit the PR to the code change, and leave out the various IntelliJ file changes.  If those are useful to propagate forward, I think they should go in a separate PR
 - could you please match the style (brace location, indentation, whitespace etc) with the existing source code
 - I don't think its warranted to add a dependency on commons-lang3 for a single method to check if a string is blank.  If we require this logic (not null, not empty, not whitespace), we can add that longhand ourselves.  My opinion however is that `isBlank` is too "wide" - I can accept that a `null` value convert to `null`, and that an _empty_ string convert to `null`, but I don't think whitespace should convert successfully to anything.

**Comment by pavanpvpk** [comment]
@gkopff extremely sorry for the delay. I have made the changes and added few new test cases as well. Let me know your feedback.

**Comment by ahmedkhalf** [comment]
@gkopff  Yo, any idea idea when this gonna be pushed? I have been impatiently waiting for three years.

**Comment by gkopff** [comment]
@ahmedkhalf the formatting fixes never got done, so that's why it was sitting there.  I've fixed the formatting myself today - but it will be a few days to work out pushing to Maven Central.  Things have changed since I last did it.

**Comment by gkopff** [comment]
@ahmedkhalf This has been released, but due to a backlog in the Maven Central indexing, it's not yet reported by the search.  It should be resolvable by Maven itself though - I've bene in contact with Sonatype about it: https://issues.sonatype.org/browse/OSSRH-82669

**Comment by gkopff** [comment]
@ahmedkhalf This is all indexed now: https://search.maven.org/artifact/com.fatboyindustrial.gson-javatime-serialisers/gson-javatime-serialisers/1.1.2/jar

**Comment by ahmedkhalf** [comment]
Thank you!

But now even though the tests are passing I am getting a warning:

```java
```

**Comment by gkopff** [comment]
As the warning says, that's a Gson issue.  I don't think Gson will ever address it.  Moshi appears to be the successor to Gson, as per: https://github.com/google/gson/issues/1821

**Pull request merged**
